language: php

php:
  - 8.0

services:
  - docker

before_install:
  - cd laradock
  - docker-compose up -d nginx mysql elasticsearch redis
  - docker-compose --file ./docker-compose.yml exec workspace composer install
  - docker-compose --file ./docker-compose.yml exec workspace npm install --no-bin-links
  - docker-compose --file ./docker-compose.yml exec workspace php artisan db:create laravel_cars
  - docker-compose --file ./docker-compose.yml exec workspace php artisan elasticsearchindexadd:cars
  - docker-compose --file ./docker-compose.yml exec workspace php artisan migrate
  - docker-compose --file ./docker-compose.yml exec workspace php artisan db:seed --class=PermissionTableSeeder
  - docker-compose --file ./docker-compose.yml exec workspace php artisan db:seed --class=CreateAdminUserSeeder

script:
  - docker-compose --file ./docker-compose.yml exec workspace ./vendor/bin/phpunit