language: php

dist: bionic

php:
  - 7.3

services:
  - mysql

before_script:
  - cd laradock
  - wsl -d docker-desktop
  - sysctl -w vm.max_map_count=262144
  - exit
  - docker-compose up -d nginx mysql phpmyadmin elasticsearch mailhog rabbitmq redis
  - docker-compose exec workspace bash

script:
  - phpunit
