language: php

dist: bionic

php:
  - 7.3

services:
  - mysql

before_script:
  - cd cars
  - cp .env.example .env
  - mysql -e 'CREATE DATABASE laravel;'
  - composer self-update
  - composer install
  - php artisan key:generate
  - php artisan migrate

script:
  - phpunit
