language: php

php:
  - 8.0

services:
  - docker

before_install:
  - cd laradock
  - docker-compose up -d nginx mysql
  - docker-compose --file ./laradock/docker-compose.yml exec workspace composer install

script:
  - docker-compose --file ./laradock/docker-compose.yml exec workspace ./vendor/bin/phpunit